
export const items = [
    {
      "name": "Mixed Gemstone Stering Silver Ring",
      "price": 1973.33,
      "color": "gold",
      "image": "https://i.postimg.cc/jSFqYBPH/Removal-845-1-1.png",
    },
    {
      "name": "Chrome Hearts Plus Cross Allover Print Horseshoe Logo Hoodie 'Black'",
      "price": 1000,
      "color": "gold",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/087/710/933/original/1190103_00.png.png?action=crop&width=360",
    },
    {
      "name": "Acer Gaming Desktop Predator Orion 3000",
      "price": 949,
      "color": "gold",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/83-101-901-19.png",
    },
    {
      "name": "BAPE Type 1 Bapex 'Green'",
      "price": 820,
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/081/483/898/original/1089405_00.png.png?action=crop&width=360",
      "color": "gold",
    },
    {
      "name": "Bottega Veneta Ski Goggles 'Green'",
      "price": 785,
      "color": "gold",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/079/652/190/original/1063266_00.png.png?action=crop&width=360",
    },
    {
      "name": "Saint Laurent Tiny Cassandre Credit Card Wallet 'Greyish Brown'",
      "price": 443,
      "color": "gold",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/092/195/372/original/1268717_00.png.png?action=crop&width=360",
    },
    {
      "name": "PS5 Console White",
      "price": 373,
      "color": "gold",
      "image": "https://i.postimg.cc/bNXrNkMN/Untitled.png",
    },
  
    {
      "name": "Casio GShock Dragonball Z GA-110JDB1A4",
      "price": 307.3,
      "color": "gold",
      "image": "https://i.postimg.cc/pLvDyprz/removal.png",
    },
    {
      "name": "Apple Watch Series 5 (GPS + Cellular, 40MM)",
      "price": 301.3,
      "color": "gold",
      "image": "https://i.postimg.cc/43thXGbn/Untitled.png",
    },
    {
      "name": "Apple IPHONE 11 Matte Black Fullsize",
      "price": 291,
      "color": "gold",
      "image": "https://i.postimg.cc/WbWZnX1p/Untitled.png",
    },
    {
      "name": "The Powerpuff Girls x Dunk Low Pro SB QS 'Buttercup'",
      "price": 283,
      "color": "gold",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/095/942/929/original/1252845_00.png.png?width=100",
    },
    {
      "name": "Nike Air Force 1 Low Multi-Swoosh Black Crimson",
      "price": 276,
      "color": "gold",
      "image": "https://i.postimg.cc/pdCwtFgg/image-17-1-1.png",
    },
    {
      "name": "Air Jordan 1 Retro High '85 OG 'Metallic Burgundy'",
      "price": 241,
      "color": "gold",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/096/293/508/original/BQ4422_161.png.png?width=100",
    },
    {
      "name": "Kobe 8 Protro 'Radiant Emerald'",
      "price": 228,
      "color": "red",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/097/654/763/original/1210578_00.png.png?width=100",
    },
    {
      "name": "Zoom Kobe 6 Protro 'Reverse Grinch'",
      "price": 219,
      "color": "red",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/095/313/945/original/1124766_00.png.png?width=100",
    },
    {
      "name": "Air Jordan 3 Retro SE 'Craft Ivory'",
      "price": 212,
      "color": "red",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/097/217/890/original/1301503_00.png.png?width=100",
    },
    {
      "name": "GIGABYTE X670E AORUS PRO X AM5 AMD Motherboard",
      "price": 210,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/13-145-485-01.png",
    },
    {
      "name": "Sp5der Beluga Hoodie 'Grey'",
      "price": 200,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/087/250/471/original/1185693_00.png.png?action=crop&width=360",
    },
    {
      "name": "Burberry Collared Sweater",
      "price": 198,
      "color": "purple",
      "image": "https://postimg.cc/Y43cP4Bw",
    },
    {
      "name": "Air Foamposite One 'Anthracite' 2023",
      "price": 192,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/094/716/194/original/1277513_00.png.png?width=100",
    },
    {
      "name": "Air Jordan 3 Retro 'Fear' 2023",
      "price": 167,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/094/065/966/original/1128539_00.png.png?width=100",
    },
    {
      "name": "Air Max Plus OG 'Voltage Purple' 2024",
      "price": 162,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/097/304/814/original/1304924_00.png.png?width=100",
    },
    {
      "name": "BAPE Color Camo Big Ape Head Tee 'Black/Red'",
      "price": 156,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/062/284/193/original/837549_00.png.png?action=crop&width=750",
    },
    {
      "name": "Acer 27in 170Hz 2K Gaming Monitor",
      "price": 155,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/24-011-452-01.png",
    },
    {
      "name": "Apple Pencil (2nd generation)",
      "price": 153,
      "color": "purple",
      "image": "https://i.postimg.cc/6qBZHPZq/removal.png",
    },
    {
      "name": "Jean Paul Gaultier La Belle Eau de Parfum Spray 100ml",
      "price": 144.3,
      "color": "purple",
      "image": "https://i.postimg.cc/P550ZFvX/removal.png",
    },
    {
      "name": "A Ma Maniére x Wmns Air Jordan 5 Retro 'Dawn'",
      "price": 137.3,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/095/078/025/original/1243222_00.png.png?width=100",
    },
    {
      "name": "Apple Airpod Pro 2nd Generation White",
      "price": 135.3,
      "color": "purple",
      "image": "https://i.postimg.cc/m28YnT8s/Untitled.png",
    },
    {
      "name": "Burberry Striped Bucket Hat",
      "price": 133.3,
      "color": "purple",
      "image": "https://i.postimg.cc/43HffwQr/removal-ai-6b33c3cf-8441-4b95-ab92-01b8a7cc0993-image-1-1.png",
    },
    {
      "name": "Chrome Hearts Underwear",
      "price": 133.0,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/074/556/346/original/994931_00.png.png?action=crop&width=360",
    },
    {
      "name": "Corsair MP600 CORE XT SSD",
      "price": 132,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/20-236-988-01.png",
    },
    {
      "name": "Acer Nitro 31.5in Gaming Monitor Curved",
      "price": 125,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/24-011-456-04.png",
    },
    {
      "name": "Wmns Air Force 1 Low 'Valentine's Day 2024'",
      "price": 121,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/097/948/373/original/1362888_00.png.png?action=crop&width=360",
    },
    {
      "name": "CORSAIR XTM70 Performance Thermal Paste",
      "price": 115,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/35-181-325-01.png",
    },
    {
      "name": "AMP All In Hoodie",
      "price": 114,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/087/250/471/original/1185693_00.png.png?action=crop&width=360",
    },
    {
      "name": "Nike LeBron 3 The Shop Black University Red (2022)",
      "price": 114,
      "color": "purple",
      "image": "https://i.postimg.cc/0jKzXCBh/removal.png",
    },
    {
      "name": "Apple Magic Keyboard White FullSize Keyboard",
      "price": 103,
      "color": "purple",
      "image": "https://m.media-amazon.com/images/I/71i+D5oZPWL._AC_SX679_.jpg",
    },
    {
      "name": "Apple Iphone 8 with HomeButton Rose",
      "price": 102.5,
      "color": "purple",
      "image": "https://i.postimg.cc/KvZ7Q17f/Untitled.png",
    },
    {
      "name": "BAPE Big Ape Head Tee 'Beige'",
      "price": 102,
      "color": "purple",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/059/873/060/original/815982_00.png?action=crop&width=600",
    },
    {
      "name": "$100 Uber Eats Digital Card",
      "price": 100,
      "color": "purple",
      "image": "https://i.postimg.cc/25KPwFRs/Untitled.png",
    },
    {
      "name": "Trident 32GB (2x16) RAM RGB DDR5",
      "price": 92,
      "color": "purple",
      "image": "https://c1.neweggimages.com/ProductImageCompressAll300/20-374-351-10.png",
    },
    {
      "name": "Air Force 1 '07 'Triple White'",
      "price": 89,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/048/340/054/original/712867_00.png.png?action=crop&width=360",
    },
    {
      "name": "Dunk Low 'Polar Blue'",
      "price": 83,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/093/184/220/original/1173790_00.png.png?action=crop&width=360",
    },
    {
      "name": "Jimmy Choo Urban Hero Eau de Parfum Spray 50ml",
      "price": 79,
      "color": "blue",
      "image": "https://i.postimg.cc/9XPkkjGX/removal.png",
    },
    {
      "name": "Gucci Socks 'Camel/Dark Green'",
      "price": 74,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/093/126/707/original/1097215_00.png.png?action=crop&width=360",
    },
    {
      "name": "Supreme Handcuffs Keychain Silver",
      "price": 71,
      "color": "blue",
      "image": "https://i.postimg.cc/qqN1m900/removal.png",
    },
    {
      "name": "Supreme Glass Spray Bottle Red",
      "price": 66,
      "color": "blue",
      "image": "https://i.postimg.cc/nhb3kRWb/removal.png",
    },
    {
      "name": "Supreme Spitfire Skate Tool Red",
      "price": 61,
      "color": "blue",
      "image": "https://i.postimg.cc/Kzzfzd1L/removal.png",
    },
    {
      "name": "Fear of God Essentials Sweatpants 'Stretch Limo'",
      "price": 60,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/073/921/807/original/986347_00.png.png?action=crop&width=360",
    },
    {
      "name": "Book: Dior By Dior",
      "price": 59,
      "color": "blue",
      "image": "https://i.postimg.cc/xjRPVjqC/removal.png",
    },
    {
      "name": "Lemaire Mini Drop Earring 'Silver'",
      "price": 52,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/077/938/631/original/1036902_00.png.png?action=crop&width=360",
    },
    {
      "name": "Lemaire Mini Drop Earring 'Gold'",
      "price": 51,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/094/019/147/original/1257652_00.png.png?action=crop&width=360",
    },
    {
      "name": "Stussy Stock Tone Logo Tee 'Red'",
      "price": 48,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/058/741/834/original/806236_00.png.png?action=crop&width=360",
    },
    {
      "name": "Fear of God Essentials Hoodie 'Light Oatmeal'",
      "price": 47,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/073/921/741/original/986342_00.png.png?action=crop&width=360",
    },
    {
      "name": "Supreme Audubon Bird Call Red",
      "price": 46,
      "color": "blue",
      "image": "https://i.postimg.cc/xCzRMLPT/removal.png",
    },
    {
      "name": "Market Smiley Sun Dye Sweatpants 'Yellow Blue Tie Dye'",
      "price": 41,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/070/284/539/original/923343_00.png.png?action=crop&width=360",
    },
    {
      "name": "Pleasures Puppies Hoodie 'Black'",
      "price": 39,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/085/739/377/original/1091523_00.png.png?action=crop&width=360",
    },
    {
      "name": "Fear of God Essentials Sweatpants 'Dark Oatmeal'",
      "price": 38.9,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/073/921/802/original/986345_00.png.png?action=crop&width=360",
    },
    {
      "name": "Wii Console with Controller and Strap",
      "price": 35,
      "color": "blue",
      "image": "https://i.postimg.cc/DfGpR4XK/Untitled.png",
    },
    {
      "name": "Off-White New Logo Face Mask Black/White",
      "price": 33.75,
      "color": "blue",
      "image": "https://i.postimg.cc/FHwND44F/Removal-87-1-1.png",
    },
    {
      "name": "Razer DeathAdder Essential Gaming Mouse",
      "price": 33,
      "color": "blue",
      "image": "https://i.postimg.cc/CxxzWYXj/removal.png",
    },
    {
      "name": "Mr Beast Basketball",
      "price": 32,
      "color": "blue",
      "image": "https://i.postimg.cc/g0wnNWBN/removal.png",
    },
    {
      "name": "Market Cali Lock Gradient Sweatpants 'Black Overdye/Bodye'",
      "price": 31,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/070/284/582/original/923353_00.png.png?action=crop&width=360",
    },
    {
      "name": "Supreme Audubon Bird Call Red",
      "price": 46,
      "color": "blue",
      "image": "https://i.postimg.cc/xCzRMLPT/removal.png",
    },
    {
      "name": "Palace Polartec Powerstretch Gloves 'Orange'",
      "price": 21,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/093/630/347/original/1292495_00.png.png?action=crop&width=360",
    },
    {
      "name": "Advisory Board Crystals Hologram Beanie 'Green'",
      "price": 19,
      "color": "blue",
      "image": "https://image.goat.com/transform/v1/attachments/product_template_pictures/images/093/908/132/original/1241536_00.png.png?action=crop&width=360",
    },
    {
      "name": "Bape Crew socks, Red",
      "price": 15,
      "color": "blue",
      "image": "https://i.postimg.cc/NGnGCmYk/Removal-304-1.png",
    },
    {
      "name": "CROCS THE OFFICE DUNDER MIFFLIN LOGO CHARM",
      "price": 7,
      "color": "blue",
      "image": "https://i.postimg.cc/D0pcL5bD/Removal-207-1-1-removebg-preview.png",
    },
    {
      "name": "Solanaspin $2.50 Voucher",
      "price": 2.5,
      "color": "blue",
      "image": "https://i.postimg.cc/VsJ4cPQP/Untitled.png320d93d4d5de31ea95528cc20b7d706908862585b18ee7428c0f0dadfe&format=webp&quality=lossless&",
    },
    {
      "name": "Solanaspin $1.00 Voucher",
      "price": 1,
      "color": "grey",
      "image": "https://i.postimg.cc/fb6njjYV/Untitled.png96d6b91c464354be4c67be6790642cf7c54d3f1fcfcb74189c13d4310e&format=webp&quality=lossless&",
    },
    {
      "name": "Solanaspin $0.50 Voucher",
      "price": 0.5,
      "color": "grey",
      "image": "https://i.postimg.cc/rw7RW3Zx/Untitled.png558855a780135adef6d6c9174d2c3783a109c09997cec7a2f8ca8a4ee2&format=webp&quality=lossless&",
    },
    {
      "name": "Solanaspin $0.25 Voucher",
      "price": 0.25,
      "color": "grey",
      "image": "https://i.postimg.cc/QxpQXXfw/Untitled.png7171339a2992186728433d1ebc595e2e78cb254086fc883242ece7499b&format=webp&quality=lossless&",
    },
    {
      "name": "Solanaspin $0.01 Voucher",
      "price": 0.01,
      "color": "grey",
      "image": "https://i.postimg.cc/5tr82jL5/Untitled.pnge40a3558400403cbb4e92e3a7db9d4bac002165df68159e33cdc341ea&format=webp&quality=lossless&",
    },
    // other items...
  ];